-- 026: Doctor Prep Report Persistence + Insight Dismissals

-- ── Doctor Prep Reports ───────────────────────────────────────────────────
-- Stores generated health summary reports so they can be retrieved later.

CREATE TABLE IF NOT EXISTS doctor_prep_reports (
    id           UUID         DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id      UUID         NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    generated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    date_range   JSONB        NOT NULL,   -- {"start": "YYYY-MM-DD", "end": "YYYY-MM-DD"}
    days         INT          NOT NULL DEFAULT 30,
    report_data  JSONB        NOT NULL,   -- full serialised DoctorPrepReport JSON
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_doctor_prep_reports_user
    ON doctor_prep_reports (user_id, created_at DESC);

ALTER TABLE doctor_prep_reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY dpr_select ON doctor_prep_reports
    FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY dpr_insert ON doctor_prep_reports
    FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY dpr_delete ON doctor_prep_reports
    FOR DELETE USING (auth.uid() = user_id);

COMMENT ON TABLE doctor_prep_reports IS 'Persisted doctor-visit prep reports generated by the app';

-- ── Dismissed Insights ────────────────────────────────────────────────────
-- Tracks which insights a user has explicitly dismissed so they are filtered
-- from future GET /insights responses.

CREATE TABLE IF NOT EXISTS dismissed_insights (
    id           UUID         DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id      UUID         NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    insight_id   VARCHAR(200) NOT NULL,
    dismissed_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, insight_id)
);

CREATE INDEX IF NOT EXISTS idx_dismissed_insights_user
    ON dismissed_insights (user_id);

ALTER TABLE dismissed_insights ENABLE ROW LEVEL SECURITY;

CREATE POLICY di_select ON dismissed_insights
    FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY di_insert ON dismissed_insights
    FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY di_delete ON dismissed_insights
    FOR DELETE USING (auth.uid() = user_id);

COMMENT ON TABLE dismissed_insights IS 'Insight IDs dismissed by users; filtered from GET /insights';
